- name: instalando o apache no Debian
  apt:
   name: apache2
   state: present
   update_cache: yes
  when: ansible_os_family == "Debian"

- name: instalando o apache no RedHat
  yum:
   name: httpd
   state: present
  when: ansible_os_family == "RedHat"
