#- name: download repo puppet Debian
#  get_url:
#   url: https://apt.puppetlabs.com/puppet5-release-xenial.deb
#   dest: /tmp/puppet.deb
#  when: ansible_os_family == "Debian"

#- name: instala o repositorio Debian
#  apt:
#   deb: /tmp/puppet.deb
#  when: ansible_os_family == "Debian"

#- name: download repo puppet RedHat
#  get_url:
#   url: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
#   dest: /tmp/puppet.rpm
#  when: ansible_os_family == "RedHat"

#- name: instala o repositorio RedHat
#  yum:
#   name: /tmp/puppet.rpm
#  when: ansible_os_family == "RedHat"

#- name: instalando puppet agent 
#  package:
#   name: puppet-agent
#   state: present
#   update_cache: yes

- name: Instalando package em todas as maquinas
  package:
   name: puppet-agent
   state: present
   update_cache: yes
