---

- name: instalando somente no Debian
  hosts: all
  tasks:
   - name: instalando pacotes
     apt:
      name: "{{item}}"
     with_items:
      - vim
      - sl
      - nano
      - dnsutils
     when: ansible_os_family == "Debian"
