---

- name: Criando usuarios do SO
  hosts: all
  tasks:
   - name: Criando os usuarios no servidor
     user:
      name: "{{ item }}"
      shell: /bin/bash
     with_items:
      - vaca
      - boi
      - jorge
      - judith
