---
# tasks file for pacotes
- name: instalando pacotes
  package:
   name: "{{ item }}"
   state: present
  with_items:
   - vim
   - nano
   - sl
   - cowsay

- name: instalando o apel-release
  package:
   name: epel-release
   state: present
  when: ansible_os_family == "RedHat"

